/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.List;
import javax.swing.JTable;
import models.Personaje;

/**
 *
 * @author verena312
 */
public class BattleField extends javax.swing.JFrame {

    private List<Personaje> equipo1;
    private List<Personaje> equipo2;
    
    
    public BattleField(List<Personaje> equipo1, List<Personaje> equipo2) {
        initComponents();
        lbGuillotine.setVisible(false);
        
        this.equipo1=equipo1;
        this.equipo2=equipo2;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPersonajeEquipo2 = new javax.swing.JTable() {
            public Class getColumnClass(int column){
                return getValueAt(0, column).getClass();
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPersonajeEquipo1 = new javax.swing.JTable() {
            public Class getColumnClass(int column){
                return getValueAt(0, column).getClass();
            }
        };
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaInfo = new javax.swing.JTable() {
            public Class getColumnClass(int column){
                return getValueAt(0, column).getClass();
            }
        };
        Inicio = new javax.swing.JLabel();
        lbatk = new javax.swing.JLabel();
        lbGuillotine = new javax.swing.JLabel();
        lbheal1 = new javax.swing.JLabel();
        Lbimg2 = new javax.swing.JLabel();
        Lbimg1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campo de Batalla");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/Logo.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaPersonajeEquipo2.setBackground(new java.awt.Color(0, 0, 0));
        TablaPersonajeEquipo2.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        TablaPersonajeEquipo2.setForeground(new java.awt.Color(153, 0, 153));
        TablaPersonajeEquipo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Personaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPersonajeEquipo2.setToolTipText("Selecione un Pj para Borrar con Del.");
        TablaPersonajeEquipo2.setGridColor(new java.awt.Color(255, 153, 0));
        TablaPersonajeEquipo2.setRowHeight(130);
        TablaPersonajeEquipo2.setSelectionForeground(new java.awt.Color(255, 0, 0));
        TablaPersonajeEquipo2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaPersonajeEquipo2.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(TablaPersonajeEquipo2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 140, 570));

        TablaPersonajeEquipo1.setBackground(new java.awt.Color(0, 0, 0));
        TablaPersonajeEquipo1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        TablaPersonajeEquipo1.setForeground(new java.awt.Color(153, 0, 153));
        TablaPersonajeEquipo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Personaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPersonajeEquipo1.setToolTipText("Selecione un Pj para Borrar con Del.");
        TablaPersonajeEquipo1.setGridColor(new java.awt.Color(255, 153, 0));
        TablaPersonajeEquipo1.setRowHeight(130);
        TablaPersonajeEquipo1.setSelectionForeground(new java.awt.Color(255, 0, 0));
        TablaPersonajeEquipo1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaPersonajeEquipo1.setShowHorizontalLines(false);
        jScrollPane2.setViewportView(TablaPersonajeEquipo1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 140, 570));

        TablaInfo.setBackground(new java.awt.Color(0, 0, 0));
        TablaInfo.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        TablaInfo.setForeground(new java.awt.Color(153, 0, 153));
        TablaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ataque", "Vida", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaInfo.setToolTipText("Selecione un Pj para Borrar con Del.");
        TablaInfo.setGridColor(new java.awt.Color(255, 153, 0));
        TablaInfo.setRowHeight(130);
        TablaInfo.setSelectionForeground(new java.awt.Color(255, 0, 0));
        TablaInfo.setShowHorizontalLines(false);
        jScrollPane3.setViewportView(TablaInfo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 480, 130));

        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/Logo.png"))); // NOI18N
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 100, 100));

        lbatk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/attack.png"))); // NOI18N
        getContentPane().add(lbatk, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 70, 70));

        lbGuillotine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/Guillotine.png"))); // NOI18N
        getContentPane().add(lbGuillotine, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 70, 70));

        lbheal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/heal.png"))); // NOI18N
        getContentPane().add(lbheal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 70, 70));

        Lbimg2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lbimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/characters/Aldeano.jpg"))); // NOI18N
        getContentPane().add(Lbimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 140, 210));

        Lbimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/characters/Aldeano.jpg"))); // NOI18N
        getContentPane().add(Lbimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 140, 210));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/background.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleField(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Lbimg1;
    private javax.swing.JLabel Lbimg2;
    private javax.swing.JTable TablaInfo;
    private javax.swing.JTable TablaPersonajeEquipo1;
    private javax.swing.JTable TablaPersonajeEquipo2;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbGuillotine;
    private javax.swing.JLabel lbatk;
    private javax.swing.JLabel lbheal1;
    // End of variables declaration//GEN-END:variables
}
