/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Cuenta;
import utilities.Audio;

/**
 *
 * @author verena312
 */
public class Principal extends javax.swing.JFrame {

    private List<Cuenta> cuentas;
    private Audio backGroundSound;
    public Principal() {
        FileOutputStream fos = null;
        initComponents();
        setLocationRelativeTo(null);
        
        backGroundSound = new Audio(getClass().getResource("/Resources/sound/Backsound.wav"));
        backGroundSound.loop();
        
        /*      
        cuentas =new ArrayList<>();
        cuentas.add(new Cuenta("sync", "1234"));
        
        try {

            fos = new FileOutputStream(getClass().getResource("/Resources/Data/Cuentas.data").getPath());
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(cuentas);
            oos.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fos.close();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JLabel();
        TfUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Btentrar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guau");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/Logo.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/Logo.png"))); // NOI18N
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });
        getContentPane().add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 100, 100));

        TfUsuario.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        TfUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        TfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfUsuarioKeyReleased(evt);
            }
        });
        getContentPane().add(TfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 230, 30));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 24, 213));
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 90, 50));

        Btentrar.setText("Entrar");
        Btentrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtentrarMouseClicked(evt);
            }
        });
        getContentPane().add(Btentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/background.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked

        this.dispose();
        new Lobby(TfUsuario.getText()).setVisible(true);


    }//GEN-LAST:event_InicioMouseClicked

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void BtentrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtentrarMouseClicked
        this.dispose();
        new Lobby(TfUsuario.getText()).setVisible(true);
    }//GEN-LAST:event_BtentrarMouseClicked

    private void TfUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfUsuarioKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtentrarMouseClicked(null);
        }
    }//GEN-LAST:event_TfUsuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btentrar;
    private javax.swing.JLabel Inicio;
    private javax.swing.JTextField TfUsuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
